//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubiquitous.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamAdmin {
            get {
                return ((string)(this["SteamAdmin"]));
            }
            set {
                this["SteamAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamBot {
            get {
                return ((string)(this["SteamBot"]));
            }
            set {
                this["SteamBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchUser {
            get {
                return ((string)(this["TwitchUser"]));
            }
            set {
                this["TwitchUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sc2tvUser {
            get {
                return ((string)(this["Sc2tvUser"]));
            }
            set {
                this["Sc2tvUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamBotPassword {
            get {
                return ((string)(this["SteamBotPassword"]));
            }
            set {
                this["SteamBotPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchPassword {
            get {
                return ((string)(this["TwitchPassword"]));
            }
            set {
                this["TwitchPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sc2tvPassword {
            get {
                return ((string)(this["Sc2tvPassword"]));
            }
            set {
                this["Sc2tvPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamBotAccessToken {
            get {
                return ((string)(this["SteamBotAccessToken"]));
            }
            set {
                this["SteamBotAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamAdminId {
            get {
                return ((string)(this["SteamAdminId"]));
            }
            set {
                this["SteamAdminId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sc2tvSanitizeSmiles {
            get {
                return ((bool)(this["sc2tvSanitizeSmiles"]));
            }
            set {
                this["sc2tvSanitizeSmiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twitchSendStatus {
            get {
                return ((bool)(this["twitchSendStatus"]));
            }
            set {
                this["twitchSendStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twitchBitrateAlarm {
            get {
                return ((bool)(this["twitchBitrateAlarm"]));
            }
            set {
                this["twitchBitrateAlarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string twitchBitrateCriticalValue {
            get {
                return ((string)(this["twitchBitrateCriticalValue"]));
            }
            set {
                this["twitchBitrateCriticalValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skypeSkipGroupMessages {
            get {
                return ((bool)(this["skypeSkipGroupMessages"]));
            }
            set {
                this["skypeSkipGroupMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sc2tvPersonalizedOnly {
            get {
                return ((bool)(this["sc2tvPersonalizedOnly"]));
            }
            set {
                this["sc2tvPersonalizedOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twitchPersonalizedOnly {
            get {
                return ((bool)(this["twitchPersonalizedOnly"]));
            }
            set {
                this["twitchPersonalizedOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skypeEnabled {
            get {
                return ((bool)(this["skypeEnabled"]));
            }
            set {
                this["skypeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sc2tvEnabled {
            get {
                return ((bool)(this["sc2tvEnabled"]));
            }
            set {
                this["sc2tvEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twitchEnabled {
            get {
                return ((bool)(this["twitchEnabled"]));
            }
            set {
                this["twitchEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool steamEnabled {
            get {
                return ((bool)(this["steamEnabled"]));
            }
            set {
                this["steamEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@stm")]
        public string steamChatAlias {
            get {
                return ((string)(this["steamChatAlias"]));
            }
            set {
                this["steamChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@ttv")]
        public string twitchChatAlias {
            get {
                return ((string)(this["twitchChatAlias"]));
            }
            set {
                this["twitchChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@sc2")]
        public string sc2tvChatAlias {
            get {
                return ((string)(this["sc2tvChatAlias"]));
            }
            set {
                this["sc2tvChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@sky")]
        public string skypeChatAlias {
            get {
                return ((string)(this["skypeChatAlias"]));
            }
            set {
                this["skypeChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goodgameEnabled {
            get {
                return ((bool)(this["goodgameEnabled"]));
            }
            set {
                this["goodgameEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@gg")]
        public string goodgameChatAlias {
            get {
                return ((string)(this["goodgameChatAlias"]));
            }
            set {
                this["goodgameChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goodgamePersonalizedOnly {
            get {
                return ((bool)(this["goodgamePersonalizedOnly"]));
            }
            set {
                this["goodgamePersonalizedOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twitchLeaveJoinMessages {
            get {
                return ((bool)(this["twitchLeaveJoinMessages"]));
            }
            set {
                this["twitchLeaveJoinMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goodgameLeaveJoinMessages {
            get {
                return ((bool)(this["goodgameLeaveJoinMessages"]));
            }
            set {
                this["goodgameLeaveJoinMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goodgameSanitizeSmiles {
            get {
                return ((bool)(this["goodgameSanitizeSmiles"]));
            }
            set {
                this["goodgameSanitizeSmiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string goodgameUser {
            get {
                return ((string)(this["goodgameUser"]));
            }
            set {
                this["goodgameUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string goodgamePassword {
            get {
                return ((string)(this["goodgamePassword"]));
            }
            set {
                this["goodgamePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goodgameLoadHistory {
            get {
                return ((bool)(this["goodgameLoadHistory"]));
            }
            set {
                this["goodgameLoadHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string battlelogEmail {
            get {
                return ((string)(this["battlelogEmail"]));
            }
            set {
                this["battlelogEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@bbl")]
        public string battlelogChatAlias {
            get {
                return ((string)(this["battlelogChatAlias"]));
            }
            set {
                this["battlelogChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string battlelogPassword {
            get {
                return ((string)(this["battlelogPassword"]));
            }
            set {
                this["battlelogPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool battlelogShowFeedEvents {
            get {
                return ((bool)(this["battlelogShowFeedEvents"]));
            }
            set {
                this["battlelogShowFeedEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool battlelogEnabled {
            get {
                return ((bool)(this["battlelogEnabled"]));
            }
            set {
                this["battlelogEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string battlelogNick {
            get {
                return ((string)(this["battlelogNick"]));
            }
            set {
                this["battlelogNick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@gtv")]
        public string gohaChatAlias {
            get {
                return ((string)(this["gohaChatAlias"]));
            }
            set {
                this["gohaChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GohaUser {
            get {
                return ((string)(this["GohaUser"]));
            }
            set {
                this["GohaUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GohaPassword {
            get {
                return ((string)(this["GohaPassword"]));
            }
            set {
                this["GohaPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gohaSendStatus {
            get {
                return ((bool)(this["gohaSendStatus"]));
            }
            set {
                this["gohaSendStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gohaPersonalizedOnly {
            get {
                return ((bool)(this["gohaPersonalizedOnly"]));
            }
            set {
                this["gohaPersonalizedOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gohaLeaveJoinMessages {
            get {
                return ((bool)(this["gohaLeaveJoinMessages"]));
            }
            set {
                this["gohaLeaveJoinMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gohaEnabled {
            get {
                return ((bool)(this["gohaEnabled"]));
            }
            set {
                this["gohaEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GohaIRCChannel {
            get {
                return ((string)(this["GohaIRCChannel"]));
            }
            set {
                this["GohaIRCChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableXSplitStats {
            get {
                return ((bool)(this["enableXSplitStats"]));
            }
            set {
                this["enableXSplitStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableStatusServer {
            get {
                return ((bool)(this["enableStatusServer"]));
            }
            set {
                this["enableStatusServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gohaStreamControl {
            get {
                return ((bool)(this["gohaStreamControl"]));
            }
            set {
                this["gohaStreamControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gohaStreamControlOnStartExit {
            get {
                return ((bool)(this["gohaStreamControlOnStartExit"]));
            }
            set {
                this["gohaStreamControlOnStartExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool empireEnabled {
            get {
                return ((bool)(this["empireEnabled"]));
            }
            set {
                this["empireEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@etv")]
        public string empireAlias {
            get {
                return ((string)(this["empireAlias"]));
            }
            set {
                this["empireAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empireUser {
            get {
                return ((string)(this["empireUser"]));
            }
            set {
                this["empireUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empirePassword {
            get {
                return ((string)(this["empirePassword"]));
            }
            set {
                this["empirePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool empireSendStatus {
            get {
                return ((bool)(this["empireSendStatus"]));
            }
            set {
                this["empireSendStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool empirePersonalizedOnly {
            get {
                return ((bool)(this["empirePersonalizedOnly"]));
            }
            set {
                this["empirePersonalizedOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool empireLeavJoinMessages {
            get {
                return ((bool)(this["empireLeavJoinMessages"]));
            }
            set {
                this["empireLeavJoinMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool empireLoadHistory {
            get {
                return ((bool)(this["empireLoadHistory"]));
            }
            set {
                this["empireLoadHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sc2tvId {
            get {
                return ((string)(this["Sc2tvId"]));
            }
            set {
                this["Sc2tvId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool twitchCurrentChatNotify {
            get {
                return ((bool)(this["twitchCurrentChatNotify"]));
            }
            set {
                this["twitchCurrentChatNotify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool steamCurrentChatNotify {
            get {
                return ((bool)(this["steamCurrentChatNotify"]));
            }
            set {
                this["steamCurrentChatNotify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool globalOnTop {
            get {
                return ((bool)(this["globalOnTop"]));
            }
            set {
                this["globalOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool globalHideBorder {
            get {
                return ((bool)(this["globalHideBorder"]));
            }
            set {
                this["globalHideBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showSmileImages {
            get {
                return ((bool)(this["showSmileImages"]));
            }
            set {
                this["showSmileImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sc2ShowSmileImages {
            get {
                return ((bool)(this["sc2ShowSmileImages"]));
            }
            set {
                this["sc2ShowSmileImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int globalTransparency {
            get {
                return ((int)(this["globalTransparency"]));
            }
            set {
                this["globalTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sc2StreamAutoSwitch {
            get {
                return ((bool)(this["sc2StreamAutoSwitch"]));
            }
            set {
                this["sc2StreamAutoSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NeedSettingsUpgrade {
            get {
                return ((bool)(this["NeedSettingsUpgrade"]));
            }
            set {
                this["NeedSettingsUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cyberEnabled {
            get {
                return ((bool)(this["cyberEnabled"]));
            }
            set {
                this["cyberEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@cyb")]
        public string cyberAlias {
            get {
                return ((string)(this["cyberAlias"]));
            }
            set {
                this["cyberAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cyberUser {
            get {
                return ((string)(this["cyberUser"]));
            }
            set {
                this["cyberUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cyberPassword {
            get {
                return ((string)(this["cyberPassword"]));
            }
            set {
                this["cyberPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool obsRemoteEnable {
            get {
                return ((bool)(this["obsRemoteEnable"]));
            }
            set {
                this["obsRemoteEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string obsHost {
            get {
                return ((string)(this["obsHost"]));
            }
            set {
                this["obsHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isFullscreenMode {
            get {
                return ((bool)(this["isFullscreenMode"]));
            }
            set {
                this["isFullscreenMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point mainFormPosition {
            get {
                return ((global::System.Drawing.Point)(this["mainFormPosition"]));
            }
            set {
                this["mainFormPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainformTopMost {
            get {
                return ((bool)(this["mainformTopMost"]));
            }
            set {
                this["mainformTopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CenterScreen")]
        public global::System.Windows.Forms.FormStartPosition mainformStartPos {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["mainformStartPos"]));
            }
            set {
                this["mainformStartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("740")]
        public int mainformWidth {
            get {
                return ((int)(this["mainformWidth"]));
            }
            set {
                this["mainformWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("620")]
        public int mainformHeight {
            get {
                return ((int)(this["mainformHeight"]));
            }
            set {
                this["mainformHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twitchDebugMessages {
            get {
                return ((bool)(this["twitchDebugMessages"]));
            }
            set {
                this["twitchDebugMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gohaDebugMessages {
            get {
                return ((bool)(this["gohaDebugMessages"]));
            }
            set {
                this["gohaDebugMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool globalDebug {
            get {
                return ((bool)(this["globalDebug"]));
            }
            set {
                this["globalDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 9.75pt, style=Bold")]
        public global::System.Drawing.Font globalChatFont {
            get {
                return ((global::System.Drawing.Font)(this["globalChatFont"]));
            }
            set {
                this["globalChatFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color globalChatBackground {
            get {
                return ((global::System.Drawing.Color)(this["globalChatBackground"]));
            }
            set {
                this["globalChatBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color globalToolBoxBack {
            get {
                return ((global::System.Drawing.Color)(this["globalToolBoxBack"]));
            }
            set {
                this["globalToolBoxBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color globalChatTextColor {
            get {
                return ((global::System.Drawing.Color)(this["globalChatTextColor"]));
            }
            set {
                this["globalChatTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool globalChatEnableTimestamps {
            get {
                return ((bool)(this["globalChatEnableTimestamps"]));
            }
            set {
                this["globalChatEnableTimestamps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color globalTimestampForeground {
            get {
                return ((global::System.Drawing.Color)(this["globalTimestampForeground"]));
            }
            set {
                this["globalTimestampForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 9.75pt, style=Bold")]
        public global::System.Drawing.Font globalTimestampFont {
            get {
                return ((global::System.Drawing.Font)(this["globalTimestampFont"]));
            }
            set {
                this["globalTimestampFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool globalChat2Image {
            get {
                return ((bool)(this["globalChat2Image"]));
            }
            set {
                this["globalChat2Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string globalChatImageFilename {
            get {
                return ((string)(this["globalChatImageFilename"]));
            }
            set {
                this["globalChatImageFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("515, 388")]
        public global::System.Drawing.Size globalFullSize {
            get {
                return ((global::System.Drawing.Size)(this["globalFullSize"]));
            }
            set {
                this["globalFullSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("515, 388")]
        public global::System.Drawing.Size globalCompactSize {
            get {
                return ((global::System.Drawing.Size)(this["globalCompactSize"]));
            }
            set {
                this["globalCompactSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool globalSmoothScroll {
            get {
                return ((bool)(this["globalSmoothScroll"]));
            }
            set {
                this["globalSmoothScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint sc2LastMsgId {
            get {
                return ((uint)(this["sc2LastMsgId"]));
            }
            set {
                this["sc2LastMsgId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 27")]
        public global::System.Drawing.Point globalViewersLocation {
            get {
                return ((global::System.Drawing.Point)(this["globalViewersLocation"]));
            }
            set {
                this["globalViewersLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54, 0")]
        public global::System.Drawing.Point globalToolsLocation {
            get {
                return ((global::System.Drawing.Point)(this["globalToolsLocation"]));
            }
            set {
                this["globalToolsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@htv")]
        public string hashdAlias {
            get {
                return ((string)(this["hashdAlias"]));
            }
            set {
                this["hashdAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hashdUser {
            get {
                return ((string)(this["hashdUser"]));
            }
            set {
                this["hashdUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hashdPassword {
            get {
                return ((string)(this["hashdPassword"]));
            }
            set {
                this["hashdPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hashdEnabled {
            get {
                return ((bool)(this["hashdEnabled"]));
            }
            set {
                this["hashdEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool globalEnableSounds {
            get {
                return ((bool)(this["globalEnableSounds"]));
            }
            set {
                this["globalEnableSounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("offline.mp3")]
        public string globalSoundOfflineFile {
            get {
                return ((string)(this["globalSoundOfflineFile"]));
            }
            set {
                this["globalSoundOfflineFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("online.mp3")]
        public string globalSoundOnlineFile {
            get {
                return ((string)(this["globalSoundOnlineFile"]));
            }
            set {
                this["globalSoundOnlineFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool globalCounterTotal {
            get {
                return ((bool)(this["globalCounterTotal"]));
            }
            set {
                this["globalCounterTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool globalCounterCybergame {
            get {
                return ((bool)(this["globalCounterCybergame"]));
            }
            set {
                this["globalCounterCybergame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool globalCounterHashd {
            get {
                return ((bool)(this["globalCounterHashd"]));
            }
            set {
                this["globalCounterHashd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool globalCounterTwitch {
            get {
                return ((bool)(this["globalCounterTwitch"]));
            }
            set {
                this["globalCounterTwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 1")]
        public global::System.Drawing.Point globalCounterPosTwitch {
            get {
                return ((global::System.Drawing.Point)(this["globalCounterPosTwitch"]));
            }
            set {
                this["globalCounterPosTwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 21")]
        public global::System.Drawing.Point globalCounterPosHashd {
            get {
                return ((global::System.Drawing.Point)(this["globalCounterPosHashd"]));
            }
            set {
                this["globalCounterPosHashd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 41")]
        public global::System.Drawing.Point globalCounterPosCybergame {
            get {
                return ((global::System.Drawing.Point)(this["globalCounterPosCybergame"]));
            }
            set {
                this["globalCounterPosCybergame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 101")]
        public global::System.Drawing.Point globalCounterPosTotal {
            get {
                return ((global::System.Drawing.Point)(this["globalCounterPosTotal"]));
            }
            set {
                this["globalCounterPosTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color globalCounterTextColor {
            get {
                return ((global::System.Drawing.Color)(this["globalCounterTextColor"]));
            }
            set {
                this["globalCounterTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color globalCounterBackColor {
            get {
                return ((global::System.Drawing.Color)(this["globalCounterBackColor"]));
            }
            set {
                this["globalCounterBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman, 9.75pt, style=Bold")]
        public global::System.Drawing.Font globalCounterFont {
            get {
                return ((global::System.Drawing.Font)(this["globalCounterFont"]));
            }
            set {
                this["globalCounterFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%t (%s%d@%c)")]
        public string appearanceMsgFormat {
            get {
                return ((string)(this["appearanceMsgFormat"]));
            }
            set {
                this["appearanceMsgFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%t (%s@%sg)")]
        public string appearanceGrpMessageFormat {
            get {
                return ((string)(this["appearanceGrpMessageFormat"]));
            }
            set {
                this["appearanceGrpMessageFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool globalUseChroma {
            get {
                return ((bool)(this["globalUseChroma"]));
            }
            set {
                this["globalUseChroma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8080")]
        public string webPort {
            get {
                return ((string)(this["webPort"]));
            }
            set {
                this["webPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool webEnable {
            get {
                return ((bool)(this["webEnable"]));
            }
            set {
                this["webEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool lastFmEnable {
            get {
                return ((bool)(this["lastFmEnable"]));
            }
            set {
                this["lastFmEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastFmLogin {
            get {
                return ((string)(this["lastFmLogin"]));
            }
            set {
                this["lastFmLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastFmPassword {
            get {
                return ((string)(this["lastFmPassword"]));
            }
            set {
                this["lastFmPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string twitchChannel {
            get {
                return ((string)(this["twitchChannel"]));
            }
            set {
                this["twitchChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool globalCounterGoodgame {
            get {
                return ((bool)(this["globalCounterGoodgame"]));
            }
            set {
                this["globalCounterGoodgame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 81")]
        public global::System.Drawing.Point globalCounterPosGoodgame {
            get {
                return ((global::System.Drawing.Point)(this["globalCounterPosGoodgame"]));
            }
            set {
                this["globalCounterPosGoodgame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color globalPersonalMessageBack {
            get {
                return ((global::System.Drawing.Color)(this["globalPersonalMessageBack"]));
            }
            set {
                this["globalPersonalMessageBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color personalMessageColor {
            get {
                return ((global::System.Drawing.Color)(this["personalMessageColor"]));
            }
            set {
                this["personalMessageColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 9.75pt, style=Bold")]
        public global::System.Drawing.Font globalPersonalMessageFont {
            get {
                return ((global::System.Drawing.Font)(this["globalPersonalMessageFont"]));
            }
            set {
                this["globalPersonalMessageFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool obsChatSwitch {
            get {
                return ((bool)(this["obsChatSwitch"]));
            }
            set {
                this["obsChatSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chat")]
        public string obsChatSourceName {
            get {
                return ((string)(this["obsChatSourceName"]));
            }
            set {
                this["obsChatSourceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string obsChatTimeout {
            get {
                return ((string)(this["obsChatTimeout"]));
            }
            set {
                this["obsChatTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color twitchMeForeColor {
            get {
                return ((global::System.Drawing.Color)(this["twitchMeForeColor"]));
            }
            set {
                this["twitchMeForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color twitchMeBackcolor {
            get {
                return ((global::System.Drawing.Color)(this["twitchMeBackcolor"]));
            }
            set {
                this["twitchMeBackcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 9.75pt, style=Bold")]
        public global::System.Drawing.Font twitchMeFont {
            get {
                return ((global::System.Drawing.Font)(this["twitchMeFont"]));
            }
            set {
                this["twitchMeFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string generalHistoryLines {
            get {
                return ((string)(this["generalHistoryLines"]));
            }
            set {
                this["generalHistoryLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string youtubeID {
            get {
                return ((string)(this["youtubeID"]));
            }
            set {
                this["youtubeID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool youtubeEnable {
            get {
                return ((bool)(this["youtubeEnable"]));
            }
            set {
                this["youtubeEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@you")]
        public string youtubeAlias {
            get {
                return ((string)(this["youtubeAlias"]));
            }
            set {
                this["youtubeAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string youtubeLastTime {
            get {
                return ((string)(this["youtubeLastTime"]));
            }
            set {
                this["youtubeLastTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 61")]
        public global::System.Drawing.Point globalCounterPosYoutube {
            get {
                return ((global::System.Drawing.Point)(this["globalCounterPosYoutube"]));
            }
            set {
                this["globalCounterPosYoutube"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool globalCounterYoutube {
            get {
                return ((bool)(this["globalCounterYoutube"]));
            }
            set {
                this["globalCounterYoutube"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string twitchOAuthKey {
            get {
                return ((string)(this["twitchOAuthKey"]));
            }
            set {
                this["twitchOAuthKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 128")]
        public global::System.Drawing.Color cyberNickColor {
            get {
                return ((global::System.Drawing.Color)(this["cyberNickColor"]));
            }
            set {
                this["cyberNickColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("148, 17, 30")]
        public global::System.Drawing.Color empireNickColor {
            get {
                return ((global::System.Drawing.Color)(this["empireNickColor"]));
            }
            set {
                this["empireNickColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("212, 208, 200")]
        public global::System.Drawing.Color gohaNickColor {
            get {
                return ((global::System.Drawing.Color)(this["gohaNickColor"]));
            }
            set {
                this["gohaNickColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("82, 112, 156")]
        public global::System.Drawing.Color goodgameNickColor {
            get {
                return ((global::System.Drawing.Color)(this["goodgameNickColor"]));
            }
            set {
                this["goodgameNickColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54, 127, 194")]
        public global::System.Drawing.Color hashdNickColor {
            get {
                return ((global::System.Drawing.Color)(this["hashdNickColor"]));
            }
            set {
                this["hashdNickColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("187, 17, 10")]
        public global::System.Drawing.Color youtubeNickColor {
            get {
                return ((global::System.Drawing.Color)(this["youtubeNickColor"]));
            }
            set {
                this["youtubeNickColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99, 64, 164")]
        public global::System.Drawing.Color twitchNickColor {
            get {
                return ((global::System.Drawing.Color)(this["twitchNickColor"]));
            }
            set {
                this["twitchNickColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("105, 210, 255")]
        public global::System.Drawing.Color sc2NickColor {
            get {
                return ((global::System.Drawing.Color)(this["sc2NickColor"]));
            }
            set {
                this["sc2NickColor"] = value;
            }
        }
    }
}
